---
- include_vars: "{{ nodesfile }}"

- name: Add the service scripts in master
  template: src={{ item.src }} dest={{ item.dest }} owner={{ hadoop_user}} group={{ hadoop_group }}
  with_items:
    - {src: "roles/master/templates/yarn-site-master.xml", dest: "/opt/hadoop/etc/hadoop/yarn-site.xml"}

- name: Copy private key into place
  template: src=hadoop_rsa dest=/{{ hadoop_user }}/.ssh/hadoop_rsa owner={{ hadoop_user }} group={{ hadoop_group}} mode=0600

- name: Copy slaves into place
  template: src=slaves dest=/opt/hadoop/etc/hadoop/slaves owner={{ hadoop_user }} group={{ hadoop_group}}

- name: prepare known_hosts entries
  shell: ssh-keyscan -t rsa {{ item.ip }}
  with_items: "{{ nodes }}"
  register: keyscans

- name: prepare known_hosts
  lineinfile: 
    dest=/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ item.stdout }}"
    regexp="^{{ item.item.hostname }}"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}
  with_items: "{{ keyscans.results }}"

- name: prepare known_hosts entries
  shell: ssh-keyscan -t rsa 0.0.0.0
  register: keyscan_0_0_0_0

- name: add 0.0.0.0 to known_hosts for secondary namenode
  lineinfile: 
    dest=/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ keyscan_0_0_0_0.stdout }}"
    regexp="^0.0.0.0"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}

- name: download ws war
  shell: scp root@205.147.109.155:/opt/tomcat/build/eu.war /

- name: download webapp war
  shell: scp root@205.147.109.155:/opt/tomcat/build/euWs.war /
